In [2]:
print ("hello world")

hello world

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("US_Accidents_May19.csv")

In [5]:
data.set_index('ID')

,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
ID,,,,,,,,,,,,,,,,,,,,,
A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Night,Night,Night
A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Night,Night,Day
A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.010,...,False,False,False,False,True,False,Night,Night,Day,Day
A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Day,Day,Day
A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.010,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A-2243935,Bing,NaN,2,2017-08-30 20:01:40,2017-08-31 02:01:40,34.055160,-118.214070,34.058220,-118.214270,0.212,...,False,False,False,False,False,False,Night,Night,Day,Day
A-2243936,Bing,NaN,2,2017-08-30 20:01:40,2017-08-31 02:01:40,34.046740,-118.214800,34.055160,-118.214070,0.583,...,False,False,False,False,False,False,Night,Night,Day,Day
A-2243937,Bing,NaN,3,2017-08-30 20:03:10,2017-08-31 02:03:10,34.031850,-117.135910,34.025370,-117.116160,1.216,...,False,False,False,False,False,False,Night,Night,Day,Day
A-2243938,Bing,NaN,4,2017-08-30 20:49:40,2017-08-31 02:49:40,34.277860,-118.608280,34.266581,-118.640372,1.991,...,False,False,False,False,False,False,Night,Night,Night,Night
A-2243939,Bing,NaN,4,2017-08-30 20:48:10,2017-08-31 02:48:10,34.324205,-118.502123,34.310790,-118.486670,1.279,...,False,False,False,False,False,False,Night,Night,Night,Day

In [6]:
data.shape

(2243939, 49)

In [7]:
data.groupby('Source').size()

Source
Bing              516762
MapQuest         1702565
MapQuest-Bing      24612
dtype: int64